name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint-and-build:
        name: Lint & Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: 'npm'

            - name: Instalar dependências
              run: npm ci

            - name: Lint e Formatação
              run: |
                  npm run format:check
                  npm run lint

            - name: Build
              run: npm run build